version: "3"
services:
  mongoforspring:
    image: mongo:latest
    container_name: mongoforspring
    ports:
      - "27017:27017"
  dockerizedspringboot-mongodb:
    image: dockerizedspringboot-mongodb:1.0
    container_name: dockerizedspringboot-mongodb
    ports:
      - "8080:8080"
    links:
      - mongoforspring